FORMAT: 1A
HOST: https://polls.apiblueprint.org/

# go-hire

Polls is a simple API allowing consumers to view polls and vote in them.

## Main endpoint [/]

### Get [GET]

+ Response 200 (application/json)

        {
            "message": "It works!"
        }